Disable SASS lint in Jenkinsfile
This is to avoid the following error:

    + bundle exec govuk-lint-sass app/assets/stylesheets
    bundler: failed to load command: govuk-lint-sass (/var/lib/jenkins/bundles/ruby/2.2.0/bin/govuk-lint-sass)
    LoadError: cannot load such file -- scss_lint/logger
      /var/lib/jenkins/bundles/ruby/2.2.0/gems/govuk-lint-1.2.1/bin/govuk-lint-sass:7:in `require'
      /var/lib/jenkins/bundles/ruby/2.2.0/gems/govuk-lint-1.2.1/bin/govuk-lint-sass:7:in `<top (required)>'
      /var/lib/jenkins/bundles/ruby/2.2.0/bin/govuk-lint-sass:23:in `load'
      /var/lib/jenkins/bundles/ruby/2.2.0/bin/govuk-lint-sass:23:in `<top (required)>'