Remove attr_accessible from User
This method isn't available in Rails 4. Removing it avoids the following
error:

> undefined method `attr_accessible' for User:Class (NoMethodError)

The attr_accessible method was being used to protect certain attributes
from mass assignment. I'm happy for us to remove this protection given
that these Users are only used in development/test and aren't
administered through the web interface.