Add schema_name for withdrawing
Previously when using the the script `bin/withdraw_manual`, an error would occur in the content store in 'content_item.rb' with this code:

```
  def register_routes(previous_item: nil)
    return if self.schema_name.start_with?("placeholder")
    return if previous_item && previous_item.route_set == self.route_set
    self.route_set.register!
  end
```

As SpecialistPublisher still uses V1 publishing endpoints to post the gone item, no `schema_name` attribute was added which would cause this error:

```
NoMethodError (undefined method `start_with?' for nil:NilClass):
app/models/content_item.rb:134:in `register_routes'
app/models/content_item.rb:19:in `create_or_replace'
app/controllers/content_items_controller.rb:28:in `block in update'
app/controllers/content_items_controller.rb:27:in `update'
```

This commit adds the hardcoded attribute. It was briefly attempted to convert to using the V2 `unpublish` endpoint, but proved to be too much work considering that a new Manuals app will be written in future.