Patch StateMachine Gem to avoid errors
This fixes the following errors we're seeing:

> NoMethodError: protected method `around_validation' called for
> #<StateMachine::Machine:0x00000004382b98>

The patch was suggested in
https://github.com/pluginaweek/state_machine/issues/251.

It would appear that this StateMachine Gem is no longer maintained so we
might want to consider upgrading to an alternative in future.